# Generated by Django 4.2.13 on 2026-06-06 11:57

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConstitutionArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        db_index=True, unique=True, verbose_name="Numéro d'article"
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=255, verbose_name="Titre"),
                ),
                ("content", models.TextField(verbose_name="Contenu")),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("souverainete", "Souveraineté & État"),
                            ("droits_fondamentaux", "Droits & Libertés Fondamentaux"),
                            ("pouvoir_executif", "Pouvoir Exécutif"),
                            ("pouvoir_legislatif", "Pouvoir Législatif"),
                            ("pouvoir_judiciaire", "Pouvoir Judiciaire"),
                            ("organisation_territoriale", "Organisation Territoriale"),
                            ("justice_constitutionnelle", "Justice Constitutionnelle"),
                            ("finances_publiques", "Finances Publiques"),
                            ("force_armee", "Forces Armées & Sécurité"),
                            ("revision", "Révision Constitutionnelle"),
                            ("dispositions_finales", "Dispositions Finales"),
                            ("autre", "Autre"),
                        ],
                        db_index=True,
                        default="autre",
                        max_length=50,
                        verbose_name="Thème",
                    ),
                ),
                (
                    "keywords",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Mots-clés"
                    ),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True
                    ),
                ),
                (
                    "embedding",
                    models.JSONField(
                        blank=True,
                        help_text="Vecteur OpenAI text-embedding-3-small (1536 dims)",
                        null=True,
                        verbose_name="Embedding vectoriel",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="fr", max_length=10, verbose_name="Langue"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Article constitutionnel",
                "verbose_name_plural": "Articles constitutionnels",
                "ordering": ["number"],
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="article_search_vector_idx"
                    )
                ],
            },
        ),
    ]
