# Generated by Django 4.2.13 on 2026-06-07 21:19

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):
    dependencies = [
        ("constitution", "0003_pgvector_embedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="constitutionarticle",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=768,
                help_text="Vecteur Gemini text-embedding-004 (768 dims)",
                null=True,
                verbose_name="Embedding vectoriel",
            ),
        ),
    ]
