# Generated by Django 4.2.13 on 2026-06-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("constitution", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoteStatSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_votes", models.PositiveIntegerField(default=0)),
                ("maintien_count", models.PositiveIntegerField(default=0)),
                ("revision_count", models.PositiveIntegerField(default=0)),
                ("changement_count", models.PositiveIntegerField(default=0)),
                ("stats_by_province", models.JSONField(default=dict)),
                ("stats_by_location", models.JSONField(default=dict)),
                ("stats_by_age", models.JSONField(default=dict)),
                ("stats_by_gender", models.JSONField(default=dict)),
                ("stats_by_argument", models.JSONField(default=dict)),
                ("computed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Snapshot statistiques",
                "verbose_name_plural": "Snapshots statistiques",
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice",
                    models.CharField(
                        choices=[
                            ("maintien", "Maintien de la Constitution actuelle"),
                            ("revision", "Révision partielle de la Constitution"),
                            ("changement", "Changement complet de la Constitution"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Choix",
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        help_text="Maximum 2000 caractères",
                        max_length=2000,
                        verbose_name="Justification",
                    ),
                ),
                (
                    "argument_category",
                    models.CharField(
                        choices=[
                            ("juridique", "Juridique (basé sur articles)"),
                            ("politique", "Politique"),
                            ("emotionnel", "Émotionnel"),
                            ("socioeconomique", "Socio-économique"),
                            ("non_classe", "Non classé"),
                        ],
                        db_index=True,
                        default="non_classe",
                        max_length=20,
                        verbose_name="Catégorie d'argument (IA)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cited_articles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="votes_citing",
                        to="constitution.constitutionarticle",
                        verbose_name="Articles cités",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vote",
                "verbose_name_plural": "Votes",
                "ordering": ["-created_at"],
            },
        ),
    ]
