# Generated by Django 4.2.13 on 2026-06-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTPVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_hash",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="Hash téléphone"
                    ),
                ),
                ("otp_code", models.CharField(max_length=6, verbose_name="Code OTP")),
                ("is_used", models.BooleanField(default=False, verbose_name="Utilisé")),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Tentatives"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expire à")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Vérification OTP",
                "verbose_name_plural": "Vérifications OTP",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CitizenUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "phone_hash",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="Hash du téléphone",
                    ),
                ),
                (
                    "age_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("under_18", "Moins de 18 ans"),
                            ("18_25", "18 – 25 ans"),
                            ("26_35", "26 – 35 ans"),
                            ("36_50", "36 – 50 ans"),
                            ("over_50", "Plus de 50 ans"),
                        ],
                        max_length=10,
                        verbose_name="Tranche d'âge",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("M", "Homme"),
                            ("F", "Femme"),
                            ("autre", "Autre / Préfère ne pas répondre"),
                        ],
                        max_length=10,
                        verbose_name="Genre",
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("national", "RDC (national)"),
                            ("diaspora", "Diaspora (hors RDC)"),
                        ],
                        max_length=10,
                        verbose_name="Localisation",
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("kinshasa", "Kinshasa"),
                            ("kongo_central", "Kongo Central"),
                            ("kwango", "Kwango"),
                            ("kwilu", "Kwilu"),
                            ("mai_ndombe", "Maï-Ndombe"),
                            ("kasai", "Kasaï"),
                            ("kasai_central", "Kasaï Central"),
                            ("kasai_oriental", "Kasaï Oriental"),
                            ("lomami", "Lomami"),
                            ("sankuru", "Sankuru"),
                            ("maniema", "Maniema"),
                            ("south_kivu", "Sud-Kivu"),
                            ("north_kivu", "Nord-Kivu"),
                            ("ituri", "Ituri"),
                            ("haut_uele", "Haut-Uélé"),
                            ("tshopo", "Tshopo"),
                            ("bas_uele", "Bas-Uélé"),
                            ("nord_ubangi", "Nord-Ubangi"),
                            ("mongala", "Mongala"),
                            ("sud_ubangi", "Sud-Ubangi"),
                            ("equateur", "Équateur"),
                            ("tshuapa", "Tshuapa"),
                            ("tanganyika", "Tanganyika"),
                            ("haut_lomami", "Haut-Lomami"),
                            ("lualaba", "Lualaba"),
                            ("haut_katanga", "Haut-Katanga"),
                        ],
                        max_length=50,
                        verbose_name="Province",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        default="CD",
                        max_length=50,
                        verbose_name="Pays (diaspora)",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="OTP vérifié"),
                ),
                (
                    "has_voted",
                    models.BooleanField(default=False, verbose_name="A voté"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Citoyen",
                "verbose_name_plural": "Citoyens",
            },
        ),
    ]
