# Generated by Django 4.2.13 on 2026-06-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("constitution", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="Question posée")),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("fr", "Français"),
                            ("lingala", "Lingala"),
                            ("kikongo", "Kikongo"),
                            ("tshiluba", "Tshiluba"),
                        ],
                        default="fr",
                        max_length=10,
                        verbose_name="Langue",
                    ),
                ),
                (
                    "response_fr",
                    models.TextField(blank=True, verbose_name="Réponse (FR)"),
                ),
                (
                    "response_lingala",
                    models.TextField(blank=True, verbose_name="Réponse (Lingala)"),
                ),
                (
                    "tokens_used",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tokens consommés"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "articles_used",
                    models.ManyToManyField(
                        blank=True,
                        related_name="ai_queries",
                        to="constitution.constitutionarticle",
                        verbose_name="Articles utilisés",
                    ),
                ),
            ],
            options={
                "verbose_name": "Requête IA",
                "verbose_name_plural": "Requêtes IA",
                "ordering": ["-created_at"],
            },
        ),
    ]
